# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20171105_1416'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
