# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0021_delete_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, verbose_name='Сессия')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Телефон')),
                ('delivery_address', models.TextField(blank=True, default=None, null=True, verbose_name='Адрес доставки')),
                ('details', models.TextField(blank=True, default=None, null=True, verbose_name='Детали к заказу')),
                ('cost', models.IntegerField(blank=True, default=None, null=True, verbose_name='Полная стоимость заказа')),
                ('status', models.CharField(choices=[('Открыт', 'Открыт'), ('В процессе', 'В процессе'), ('Оплачен', 'Оплачен'), ('Доставлен', 'Доставлен'), ('Закрыт', 'Закрыт')], default='Открыт', max_length=2, verbose_name='Статус')),
                ('ordered_items', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.ItemsInCart')),
            ],
        ),
    ]
