# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20171120_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Сессия'),
        ),
    ]
